### ISSUE TITLE
Inconsistent behavior of main menu entries

### ISSUE THREAD

**Issue by ThomasFreedman** [raspberrypi-ui/alacarte#3]
The behavior is inconsistent with items added using the "Main Menu Editor" tool on the Raspberry Pi OS.

I have already submitted a bug report in the Gnome bug tracker, however I believe this issue is specific to the Raspberry Pi OS version of Gnome.

It creates proper .desktop files in the user's ~/.local/share/applications folder of the form alacarte-made-N.desktop (where N is a number), but they don't always appear in the main menu.

If I copy them to /usr/local/share/applications/ they don't appear there either, at least not after a logout / in.

Also the "OK" button on the Main Menu Editor is grayed out even if the "command" entry is executable. /bin/bash works, but my bash script does not, even tho #!/bin/bash is first line in it and permissions are 755

**Comment by spl237** [comment]
Very unlikely to be anything to do with our version; all the changes I made were purely cosmetic to improve the appearance, the functionality wasn't touched. Hopefully upstream will have fixes, but the problems you describe sound to me as if they aren't alacarte itself but something on your system which is failing to show the desktop files.

**Comment by spl237** [comment]
Further - there have been very few changes to alacarte over the last few years, but things seem to have woken up recently and the version in the forthcoming bullseye release of Debian looks to have changed significantly. Given that, I'm not going to be working on the existing version any more; it's not worth it this close to bullseye; I'll look at the bullseye version when we are getting that image ready for release.

**Comment by ThomasFreedman** [comment]
Perhaps you are correct, but I'm using a fresh copy of Raspberry Pi OS.

Although you foresee a new version on the horizon, is there no concept of LTS in Raspberry Pi OS?

One inconsistency is when I add a new folder in the top level it shows up in the Editor, but not in the menu, even after lx???? refresh (forgive my memory, I just woke up) Then, is disappears with no trace even in the editor (actually it may be in the "Other" folder; so why does is show up at the top level initially?)

Since lxde sorts menu items by category, why doesn't the editor provide ability to either create new categories or at least surface them in a drop down list?

Sorry is this is truly an lxde issue. I feel like a monkey in the middle game is affoot here, between Raspberry Pi OS, LXDE and Gnome.

I've been working with the Pi for 3 years now. Never noticed these types of issues when the OS was called Raspian (Debian Jessie), although much more focused on UI now which may be why.

**Comment by spl237** [comment]
> Although you foresee a new version on the horizon, is there no concept of LTS in Raspberry Pi OS?

 Long-term support is provided by taking the latest versions of software from Debian as they are released; alacarte is a Debian package, not one we have written ourselves. We do not have the resource to support older versions of the OS for anything other than upstream security patches.

The last time a change was made to this package was three years ago, and yours is the only bug report against it in that time. So if this is indeed a problem with the package - and it may well not be - it really isn't worth spending time investigating it at this point in the release cycle, when the release of a newer version is on the horizon anyway. 

There are numerous ways to manually edit the main menu, so there are ample workarounds to the problem you report - see https://wiki.lxde.org/en/Main_Menu for some suggestions.

**Comment by ThomasFreedman** [comment]
Ok, got it, and thank you for the link.
